### ISSUE TITLE
Shared bookmarks no longer appearing

### ISSUE THREAD

**Issue by mrchrisadams** [loomchild/sojourner-web#142]
hi @loomchild  - is the new shared bookmarks url working for you?

When I visit this url, I think there's somethign up with the sorting by day, as I'm now seeing a blank page. 

Here's the url I'm trying out:

https://fosdem.sojourner.rocks/2024/shared?eventIds=1678,1702,1822,1834,1885,1894,1947,1975,2052,2101,2162,2203,2211,2357,2367,2396,2411,2412,2558,2594,2614,2640,2645,2650,2707,2723,2735,2767,2818,2913,2954,2974,3009,3025,3049,3052,3062,3128,3234,3235,3286,3312,3317,3509

And here's the error message I see in the console:

```
TypeError: Cannot read properties of undefined (reading 'day')
    at EventList.vue:45:51
    at Array.filter (<anonymous>)
    at EventList.vue:45:29
    at Array.map (<anonymous>)
    at a.allDayEvents (EventList.vue:43:27)
    at t.get (vue.esm.js:4164:33)
    at t.evaluate (vue.esm.js:4265:27)
    at a.allDayEvents (vue.esm.js:4490:25)
    at a.switchTabIfNoEvents (EventList.vue:65:17)
    at a.created (EventList.vue:56:10)
    at In (vue.esm.js:3735:61)
    at an (vue.esm.js:3136:13)
    at t._init (vue.esm.js:4713:9)
    at new a (vue.esm.js:5836:18)
    at vue.esm.js:5044:12
    at init (vue.esm.js:4906:52)
    at vue.esm.js:6578:17
    at d (vue.esm.js:6532:13)
    at h (vue.esm.js:6651:17)
    at d (vue.esm.js:6555:13)
    at a.__patch__ (vue.esm.js:7082:13)
    at t._update (vue.esm.js:2870:25)
    at a.r (vue.esm.js:2980:16)
    at t.get (vue.esm.js:4164:33)
    at new t (vue.esm.js:4154:51)
    at vue.esm.js:2997:5
    at Qr.$mount (vue.esm.js:9312:12)
    at Qr.$mount (vue.esm.js:11877:18)
    at init (vue.esm.js:4907:19)
    at n (vue.esm.js:5061:9)
    at vue.esm.js:6578:17
    at d (vue.esm.js:6532:13)
    at a.__patch__ (vue.esm.js:7082:13)
    at t._update (vue.esm.js:2870:25)
    at a.r (vue.esm.js:2980:16)
    at t.get (vue.esm.js:4164:33)
    at new t (vue.esm.js:4154:51)
    at vue.esm.js:2997:5
    at Qr.$mount (vue.esm.js:9312:12)
    at Qr.$mount (vue.esm.js:11877:18)
    at init (vue.esm.js:4907:19)
    at n (vue.esm.js:5061:9)
    at vue.esm.js:6578:17
    at d (vue.esm.js:6532:13)
    at a.__patch__ (vue.esm.js:7082:13)
    at t._update (vue.esm.js:2870:25)
    at a.r (vue.esm.js:2980:16)
    at t.get (vue.esm.js:4164:33)
    at new t (vue.esm.js:4154:51)
    at vue.esm.js:2997:5
```

I'm happy to share more if it helps.

**Comment by loomchild** [comment]
Thanks for reporting, I'll look into this today.

**Comment by loomchild** [comment]
Actually it works for my personal shared list.

The issue is related to an event that is missing: https://fosdem.sojourner.rocks/2024/event/2767. I am not sure what happened, sometimes events get removed, but maybe ID has changed...(it shouldn't happen, but..).

 I'll fix the code ASAP to support this case, for now please use the URL without this event: https://fosdem.sojourner.rocks/2024/shared?eventIds=1678,1702,1822,1834,1885,1894,1947,1975,2052,2101,2162,2203,2211,2357,2367,2396,2411,2412,2558,2594,2614,2640,2645,2650,2707,2723,2735,2818,2913,2954,2974,3009,3025,3049,3052,3062,3128,3234,3235,3286,3312,3317,3509

**Comment by loomchild** [comment]
The talk was "llamafile: Collapsing the complexity of open source AI down to a single file" by Stephen Hood, on Mozilla track. I don't see it anymore in official schedule. I guess it was removed (long time ago removed tracks were just marked as removed, now I guess they are simply deleted).

**Comment by mrchrisadams** [comment]
ah, thanks for clearing that up @loomchild - i'll do as you say. This is still  a really cool feature :D

**Comment by loomchild** [comment]
@mrchrisadams The issue should be resolved, please let me know if everything works for you.

**Comment by mrchrisadams** [comment]
Hi @loomchild yes, this totally works now! Thanks!
